import threading
import time
import webbrowser
from pathlib import Path

from flask import Flask, request
from fyers_apiv3 import fyersModel

from CFGFunctions import get_property, upsert_property

ROOT = Path(__file__).resolve().parent
LOG_DIR = ROOT / "Logs"
app = Flask(__name__)
auth_code_value = None

APPID = get_property("appId")
REDIRECTURI = get_property("REDIRECT")
RESPONSE_TYPE = "code"
SECRETID = get_property("secretID")
GRANT_TYPE = "authorization_code"


@app.route("/")
def capture_code():
    global auth_code_value
    auth_code_value = request.args.get("auth_code")
    upsert_property("auth_code", auth_code_value)
    # print(f"✅ Captured auth_code: {auth_code_value}")
    return "You can close this tab now."


def run_flask():
    app.run(port=5000)


def get_auth_code():
    # Start Flask server in a separate thread
    flask_thread = threading.Thread(target=run_flask, daemon=True)
    flask_thread.start()

    # Give the server a moment to start
    time.sleep(1)

    startBrowserForAuthCode()

    # Wait for the auth_code to be captured
    while auth_code_value is None:
        time.sleep(0.5)

    return auth_code_value


def startBrowserForAuthCode():
    functionName = "getauthToken"
    """
        :param app_id: "XXXXXXXXXXX"
        :param redirect_url: "https://XXXXXX.com"
		 1. This function open this url in the browser.
		 2. This will ask you to login and will ask you to approve the app if it is not approved already.
		 3. Once that is done, it will redirect to a url (added while app creation) with the auth_code. The url will look like
		    https://www.google.com/?auth_code=eyJ0eXAiOiXXXXXGciOiJIUzI1NiJ9.eyXXXXXXXXXXXXXInN1YiI6ImF1dGhDb2XXXXXXXXXXXXXXXXXX2lkIjoiQjhQV0xWSDhUNiIsImlzcyI6ImFwaS5sb2dpbi5meWVycy5pbiIsImF1ZCI6WyJ4OjAiLCJ4OjEiLCJ4OjIiXSwidXVpZCI6ImZhOGNhYjE3ZWU4OTQzMGRhZjA1YWUxNDI2YWVkYzI4IiwiaXBBZGRyIjoiMjIzLjIzMy40Mi40NiIsImRpc3BsYXlfbmFtZSI6IkRQMDA0MDQiLCJpYXQiOjE1OTM1ODYzNzEsIm5iZiI6MTU5MzU4NjM3MX0.IMJHzQGHQgyXt_XN0AgDrMN1keR4qolFFKO6cyXTnTg&user_id=DP00404
		 4. You have to take the auth_code from the url and use that token in your generate_access_token function.
	"""

    # creating an instance appSession to generate the auth code by passing app id and redirect url as parameter
    appSession = fyersModel.SessionModel(
        client_id=APPID,
        redirect_uri=REDIRECTURI,
        response_type=RESPONSE_TYPE,
        grant_type=GRANT_TYPE,
        state="state",
        scope="",
        nonce="",
    )

    # The variable `generateTokenUrl` will have a url like https://uat-api.fyers.in/api/dev/generate-authcode?appId=B8PXXXH8T6&redirectUrl=https%3A%2F%2Fgoogle.com
    generateTokenUrl = appSession.generate_authcode()

    # This command is used to open the url in default system brower
    webbrowser.open(generateTokenUrl, new=1)


def generate_access_token(auth_code, appId, secret_key):
    functionName = "generate_access_token"
    """
	:param auth_code: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1OTM1ODY2NzEsInN1YiI6ImF1dGhDb2RlIiwiYXBwX2lkIjoiQjhQV0xWSDhUNiIsImlzcyI6ImFwaS5sb2dpbi5meWVycy5pbiIsImF1ZCI6WyJ4OjAiLCJ4OjEiLCJ4OjIiXSwidXXXXXXXXXXXYjE3ZWU4OTQzMGRhZjA1YWUxNDI2YWVkYzI4IiwiaXBBZGRyIjoiMjIzLjIzMy40Mi40NiIsImRpc3BsYXlfbmFtZSI6IkRQMDA0MDQiLCJpYXQiOjE1OTM1ODYzNzEsIm5iZiI6MTU5MzU4NjM3MX0.IMJHzQGHQgyXt_XN0AgDrMN1keR4qolFFKO6cyXTnTg"
	:param app_id: "B8PXXXXXXX"
	:param secret_key: "XXXXXXKGN0"
	:param redirect_url: "https://XXXXXX.com"
	:return: access_token: "eyJ0eXAiOiJKV1QiLCXXXX1NiJ9.eyJpYXXXXXXXXXXMsIm5iZiI6MTU5MzU4ODM3MywiZXhwIjoxNTkzNjQ5ODEzLCJpc3MiOiJhcGkuZnllcnMuaW4iLCJzdWIiOiJhY2Nlc3MiLCJhdWQiOiJ4OjAseDoxLHg6MiIsImF0X2hhc2giOiJnQUFBQUFCZV9EcVZIZExMMTAzTVpVN1NYSkZfR2p5R3hidzMtTVVhb0VEMGI0QUVvNjFsR24tREY2OFU5cXhuNzd0UXVoOVVJalYtNm9MVXhINVFfWE1WTEJfRXpROGV2clJmUzlNUXB0Y2J5c2ltN1drWllZTT0iLCJkaXNwbGF5X25hbWUiOiJQSVlVU0ggUkFKRU5EUkEgS0FQU0UiLCJmeV9pZCI6IkRQMDA0MDQifQ.cAfrj2TxAyb8A_9DfiCb1hLIZg_mH-xvP3Ybnj3a4AE"

	1.this function takes the param and return the access_token
	2.the access_token created will be used further .(in fyersModel)]
	3. one can get the auth_code from the url generated by getauthToken function (from auth_code= ..... &user_Id=xxxxxx before &)
	"""
    # creating an instance appSession by passing app id,secret key and redirect url as parameter
    appSession = fyersModel.SessionModel(
        client_id=appId, secret_key=secret_key, grant_type="authorization_code"
    )

    # we need to pass the auth code in set_token method
    appSession.set_token(auth_code)
    # generate_token function will return us the access token and we store in variable "access_token"
    access_token = appSession.generate_token()
    upsert_property("access_token", access_token.get("access_token"))
    return access_token


def login(tbt=False):
    auth_code = get_property("auth_code")
    accessToken = get_property("access_token")
    LOG_DIR.mkdir(parents=True, exist_ok=True)

    fyers = fyersModel.FyersModel(
        client_id=APPID, is_async=False, token=accessToken, log_path=str(LOG_DIR)
    )
    response = fyers.get_profile()

    print("Connectivity Status: ", response.get("s"))

    if response.get("code") in [-8, -15, -16, -17, -209, -437, -300]:
        print("Login expired or invalid. Need to re-login.")
        auth_code = get_auth_code()
        accessToken = generate_access_token(auth_code, APPID, SECRETID)
        # print("\n \nAccess Token: ", accessToken)
        accessToken = accessToken.get("access_token")
        fyers = fyersModel.FyersModel(
            client_id=APPID, is_async=False, token=accessToken, log_path=str(LOG_DIR)
        )

    if tbt == False:
        return fyers
    else:
        from fyers_apiv3.FyersWebsocket.tbt_ws import FyersTbtSocket

        fyers = FyersTbtSocket(
            access_token=accessToken,
            write_to_file=False,
            log_path=str(LOG_DIR),
            # on_open=onopen,
            # on_close=onclose,
            # on_error=onerror,
            # on_depth_update=on_depth_update,
            # on_error_message=onerror_message
        )
        return fyers


CaptureCode = capture_code
RunFlask = run_flask
GetAuthCode = get_auth_code
StartBrowserForAuthCode = startBrowserForAuthCode
GenerateAccessToken = generate_access_token
Login = login
